// (C) 2019 FOTEC Forschungs- und Technologietransfer GmbH
// Research Subsidiary of FH Wiener Neustadt
// 
// Contact biss@fotec.at / www.fotec.at
// 
// Created:        16.09.2020 14:18
// Developer:      Gregor Faiman
// Project         SIKOSI
//
// Released under GPL-3.0-only

using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace SRPServerAPI.Model
{
    public class DataCache
    {
        /// <summary>
        /// Dictionary mapping values generated for a client session to that clients verifier.
        /// </summary>
        private Dictionary<BigInteger, ClientSessionValues> clientSessionValues;

        public DataCache()
        {
            this.clientSessionValues = new Dictionary<BigInteger, ClientSessionValues>();
        }

        /// <summary>
        /// Retrieves the client generated value A as part of the login process.
        /// </summary>
        /// <param name="clientKey">The client verifier used as a key.</param>
        /// <returns>The retrieved value.</returns>
        public byte[] ExtractClientValueA(BigInteger clientKey)
        {
            if (!this.IsKeyValid(clientKey))
                throw new ArgumentException(nameof(clientKey), "Client key was invalid.");

            return this.clientSessionValues[clientKey].PublicClientValueA;
        }

        /// <summary>
        /// Stores the public value A that was sent to the server by the client.
        /// </summary>
        /// <param name="clientKey">The dictionary key. This is the client verifier.</param>
        /// <param name="clientValue">The generated value.</param>
        /// <exception cref="ArgumentNullException">
        /// Is thrown if either client key or client value are null.
        /// </exception>
        public void StoreClientGeneratedValue(BigInteger clientKey, byte[] clientValue)
        {
            if (clientKey == null)
                throw new ArgumentNullException(nameof(clientKey), "Client key must not be null.");

            if (clientValue == null)
                throw new ArgumentNullException(nameof(clientValue), "Client value must not be null.");

            this.clientSessionValues[clientKey].PublicClientValueA = clientValue;
        }

        /// <summary>
        /// Creates a user record locally on the server in memory.
        /// If a record for the specified user already exists, no new record is created.
        /// </summary>
        /// <param name="clientKey">The client key for the dictionary.</param>
        /// <param name="username">The user name.</param>
        /// <param name="clientGeneratedValueA">The value generated by the client.</param>
        /// <returns>An empty task object.</returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown if either of the parameters are null.
        /// </exception>
        public void TryCreateUserRecord(BigInteger clientKey, string username, byte[] clientGeneratedValueA)
        {
            if (username == null)
                throw new ArgumentNullException(nameof(username), "User name must not be null.");

            if (clientGeneratedValueA == null)
                throw new ArgumentNullException(nameof(clientGeneratedValueA), "Client value must not be null.");

            if (this.clientSessionValues.Keys.Contains(clientKey))
            {
                this.clientSessionValues[clientKey].ClientUsername = username;
                this.clientSessionValues[clientKey].PublicClientValueA = clientGeneratedValueA;
            }
            else
            {
                ClientSessionValues record;

                record = new ClientSessionValues(username);
                record.PublicClientValueA = clientGeneratedValueA;

                this.clientSessionValues.Add(clientKey, record);
            }
        }

        /// <summary>
        /// Retrieves the generated public server value for a client.
        /// </summary>
        /// <param name="clientKey">The client verifier.</param>
        /// <returns>The values for this clients session.</returns>
        /// <exception cref="ArgumentNullException">
        /// Is thrown if client key is null.
        /// </exception>
        public byte[] RetrieveServerPublicValue(BigInteger clientKey)
        {
            if (!this.IsKeyValid(clientKey))
                throw new ArgumentException(nameof(clientKey), "Client key was invalid.");

            return this.clientSessionValues[clientKey].PublicServerValue;
        }

        /// <summary>
        /// Retrieves the generated private server value for a given client..
        /// </summary>
        /// <param name="clientKey">The client verifier.</param>
        /// <returns>The values for this clients session.</returns>
        /// <exception cref="ArgumentNullException">
        /// Is thrown if client key is null.
        /// </exception>
        public byte[] RetrieveServerPrivateValue(BigInteger clientKey)
        {
            if (!this.IsKeyValid(clientKey))
                throw new ArgumentException(nameof(clientKey), "Client key was invalid.");

            return this.clientSessionValues[clientKey].PrivateServerValue;
        }

        /// <summary>
        /// Stores the public and prviate server values.
        /// </summary>
        /// <param name="clientVerifier">The clients key.</param>
        /// <param name="privateServerValue">Thep rivate server value.</param>
        /// <param name="publicServerValue">The public server value.</param>
        public void StoreServerValues(BigInteger clientVerifier, byte[] privateServerValue, byte[] publicServerValue)
        {
            if (!this.IsKeyValid(clientVerifier))
                throw new ArgumentException(nameof(clientVerifier), "Invalid client key.");

            this.clientSessionValues[clientVerifier].PrivateServerValue = privateServerValue;
            this.clientSessionValues[clientVerifier].PublicServerValue = publicServerValue;
        }

        public void StoreSessionKey(BigInteger clientVerifier, byte[] sessionKey)
        {
            if (!this.IsKeyValid(clientVerifier))
                throw new ArgumentException("Invalid client key.");

            this.clientSessionValues[clientVerifier].SessionKey = sessionKey;
        }

        public byte[] ExtractSessionKey(BigInteger clientVerifier)
        {
            if (!this.IsKeyValid(clientVerifier))
                throw new ArgumentException("Invalid client key.");

            return this.clientSessionValues[clientVerifier].SessionKey;
        }

        /// <summary>
        /// Checks whether the specified dictionary key is valid.
        /// </summary>
        /// <param name="clientKey">The client verifier used as a dictionary key.</param>
        /// <returns>Whether the key is valid.</returns>
        private bool IsKeyValid(BigInteger clientKey)
        {
            if (clientKey != null && this.clientSessionValues.ContainsKey(clientKey))
                return true;
            else
                return false;
        }
    }
}
